version: 2

sources:
  - name: analytics
    schema: analytics
    tables:
      - name: fact_orders
      - name: fact_payments
      - name: fact_returns
      - name: fact_web_events
      - name: fact_inventory
      - name: dim_customers
      - name: dim_products
      - name: dim_date
      - name: dim_region
      - name: dim_channel
